"$schema" = 'https://starship.rs/config-schema.json'

[git_branch]
style = "purple"

[gcloud]
disabled = true

[aws]
disabled = true

[container]
disabled = true

[env_var.CODER_WORKSPACE_NAME]
format = "[ $env_value]($style) "
style = "bold cyan"

[kubernetes]
disabled = false
style = "bold fg:18 bg:117"

[cmd_duration]
min_time = 500
